### ISSUE TITLE
Feature Request - Shared Campaigns

### ISSUE THREAD

**Issue by AlexanderHeidrich** [zzorba/ArkhamCards#150]
Hello there,

I'm hosting private campaigns with 3 friends (with four webcams :D). This means that I have created a campaign and created 4 Decks in the app. (And I love this feature!!) 
My friends are also storing their decks on ArkhamDB and here I have a problem.

Currently I'm able to clone their decks into my ArkhamDB hub to be able to use "their" decks in the campaign.
But now, as soon as the campaign advances, my friends improve their decks but the new state is not available in the campaign, as my clone is not up to date. Also I cant give them real information about available EXP, etc.

So in general it is very hard to track progress as a "campaign game master".
I know that e.g. EXP-updates of others decks are only possible if you would authenticate as the owner, but receiving a deck over the ID should enable getting the upgrade history, etc.

So would it be possible/would it make sense to just link/follow decks in the deck overview? Or at least reference decks in the campaign over the id.
What do you think?

**Comment by zzorba** [comment]
This is actually the feature I'm currently working on (and the reason you see some strings related to friends/account names in the server project).

It's note QUITE ready yet, but I'm hoping by the middle of March there will be a way to 1) upload campaigns and sync them between your devices, 2) invite friends to share in a campaign, where they can add their own decks to it.

In the meantime, what I've found that works here is add the other players investigators as 'just investigators (no decks)', which lets you track the XP they spend, but they can track the deck on their own account. But its much less satisfying, which is why I'm working on the campaign sharing feature.

**Comment by AlexanderHeidrich** [comment]
Ah cool! I was not quite sure if these campaign stuff I have seen in the code were about the ArkhamCards.com Multiplayer Events. 
i‘m excited!
