### ISSUE TITLE
[Bug report] 'upgrade card' or 'compute xp cost' error

### ISSUE THREAD

**Issue by derornos** [zzorba/ArkhamCards#165]
Thank you for your hard work and dedication.

I would like to apologize for my poor english in the first place.

I played mystic - akachi in ptc campaign.
(she had two arcane research cards.)

It happened after upgrading 1x 'Shrivelling(Lv 0)' & 1x 'Fearless(Lv 0)' to 1x 'Shrivelling(Lv 3)' & 1x 'Fearless(Lv 2)' with 3xp

but app displayed 5/3xp in lastest upgrade/deck section. (2xp over-spent)

![ac1](https://user-images.githubusercontent.com/15874357/113800037-30389a00-9791-11eb-99ac-b335aaa08326.jpg)

2x arcane research cards didn't work!

At latest upgrade/deck section, i found something a little strange.

Upgraded section -> 'Fearless(Lv 0)' -1, 1x 'Fearless(Lv 2)' +1
Added section ->'Shrivelling(Lv 3)' +1
Removed section -> 1x 'Shrivelling(Lv 0)' -1

![ac2](https://user-images.githubusercontent.com/15874357/113800092-49414b00-9791-11eb-81c6-c6a193dfc7da.jpg)

I pressed 'View on ArkhamDB' button, but it worked fine on that site.

![ad1](https://user-images.githubusercontent.com/15874357/113800110-52cab300-9791-11eb-9237-af3ea4f49ea0.jpg)

**Comment by zzorba** [comment]
Thank you for the detailed error report, very helpful.

I've identified the issue, there was a situation where I was checking 'name==name' (i.e. comparing the translated names), instead of testing for their 'untranslated' name.  This means it would break if there were partially translated cards, or in this case the Korean translation is slightly different in the 4th character.  

I'll update this in the next release, probably sometime this weekend.

**Comment by derornos** [comment]
I'm glad you told me that my report was helpful. thx. XD

Cheer up!
