### ISSUE TITLE
[Question] How to extract logs for one campaign?

### ISSUE THREAD

**Issue by derornos** [zzorba/ArkhamCards#411]
There was a bug in the app where additional experience points were gained during the rtptc campaign.

I would like to report this, but I would like to send a log for one campaign.

However, I can currently only send logs for all campaigns I own. What would you like me to do?

**Comment by zzorba** [comment]
If you send me the backup and the name of the campaign that was broken, I can take a look at it.

**Comment by derornos** [comment]
[ACB-2022-09-13.zip](https://github.com/zzorba/ArkhamCards/files/9554752/ACB-2022-09-13.zip)

1. Earned 7 xp for the second scenario.

2. When I tried to edit the deck, joe got 11 xp, so I manually adjusted it to 7 xp.

**Comment by zzorba** [comment]
So I think I see what happened here -- thank you for the detailed submission.

It looks like when the first set of deck changes were saved, the XP was calculated wrong (it charged 5 XP instead of 9XP, leaving 4 over).  The changes did save though, I expect there was a race condition when the two copies of Perception(2) were added, and it hadn't recalculated the 'cost' just yet.

For now, give it a second and make sure that you see the edits on the screen.  I'm going to put in a more comprehensive fix for this race condition as well.
