### ISSUE TITLE
[Bug?] taboo + Adaptable

### ISSUE THREAD

**Issue by derornos** [zzorba/ArkhamCards#448]
I'm not sure if the Adaptable card is working well.

Gained 1 XP, added an Adaptable card to the deck, and swapped out 2 cards.

![KakaoTalk_20221213_155621550](https://user-images.githubusercontent.com/15874357/207529297-951a04a1-2430-472b-88dd-3a476b90cd53.jpg)
![KakaoTalk_20221213_155621550_01](https://user-images.githubusercontent.com/15874357/207529312-5f951cfc-dfd4-4587-af77-2f845563b0e1.jpg)

I wonder if the '1/1 XP' part is correct in the part that indicates the Latest Deck.

**Comment by zzorba** [comment]
So last I heard, there was some gray area over how Taboo should work with Adaptable.  The ruling I saw (shortly after Taboo came out), said that technically Adaptable would let you dodge the Taboo cost, but (i think the quote was) "If you are going to play like that, why are you playing Taboo".

Have you heard if there has been a newer ruling/guidance?

I think what the app is doing is this:
1) Applying that taboo swap rule to make Drawing Thin free (since it ignores the XP cost, including the additional XP cost).
2) Signum Crucis though is technically an XP card, which has been discounted by Taboo to be 2 less.  So I don't think the app is neither a) counting it towards Adpatable, since its not L0, or b) charging anything for it, since discounts are allowed to make a swap cost 0 (assuming taboo discount works the same way as Arcane Research, the minimum of 1 is not actually a minimum of 1).

So maybe correct?  But definitely a weird area?

**Comment by zzorba** [comment]
@derornos let me know what you think about the above, and if there are any rulings that suggest otherwise?

**Comment by derornos** [comment]
In this regard, I made inquiries to some Korean community users.

But I had a hard time getting a clear answer.

The main opinion was to ask questions formally and get answers.

====

After reading the comments, my personal opinion seems to be that your app implementation is correct. (Even if it doesn't make sense to use taboo.)

Adaptable
https://arkhamdb.com/card/02110

> In between each game of a campaign, you may swap up to two level 0 cards out of your deck in exchange for an **EQUAL NUMBER OF LEVEL 0 CARDS.** (You must still follow all deckbuilding rules for your investigator).

Signum Crucis
https://arkhamdb.com/rules#Experience

> (Added in FAQ, section 'Game Play', point 1.8) When purchasing a new card during campaign play, an investigator must pay a minimum of 1 experience. As a result, level 0 cards cost 1 experience to purchase. This minimum only applies when purchasing new cards. It does not permanently alter a card’s level or experience cost, and **DOES NOT APPLY WHEN UPGRADING A CARD TO A HIGHER LEVEL VERSION.**

**Comment by derornos** [comment]
![image](https://user-images.githubusercontent.com/15874357/208326633-45a1a66f-2f5d-4b85-84e3-8d55cecb77b1.png)

But I'm not sure what it means that the above 2 items have different values.

**Comment by zzorba** [comment]
Yeah, taboo + adaptable is a crazy corner case IMO.

So the difference between the two XPs is basically "how much XP it would cost to construct the deck from scratch right now" vs "how much XP you spent to do the upgrades".  Things like adaptable / arcane research might make the upgrades cheaper than the total cost of XP in the deck.

**Comment by derornos** [comment]
okay. Finally I understood. Thank you for your kindness.
