### ISSUE TITLE
[Feature Request] Shortcut for Campaign Common Rules

### ISSUE THREAD

**Issue by derornos** [zzorba/ArkhamCards#553]
Players often don't fully remember the common rules that apply within a campaign.
Some of them are unique, while others appear in multiple campaigns.

- ex1. tfa - Explore / tcu - Haunted / tic - Key, Flood Tokens / eoe - Frost token, Tekeli-li / zcf - Non-Euclidean / zdm - Scan
- ex2. Alert - tfa, tcu, tde, ... / Bonded - tcu, tde, ... / Myriad - tde, ... / Patrol - eoe, ... / Swarming - tde, ...

The former, in particular, is often tied to a special gimmick for that campaign.
If the player wants to look up a specific phrase, they need to go through the sequence 'Chaos bag screen -> Scenario screen -> Campaign main screen' and hit the `View results` button in `Campaign Setup` from the list of scenarios.

If there was a shortcut button for players to view the campaign common rules from within the campaign screens (including the chaos bag screen), I think it would improve this inconvenience.

thanks : )

**Comment by zzorba** [comment]
I like this idea a lot. Though I might need help encoding which rules are important for a given scenario (based on their rule Ids). 

If you can help me collate that, even for one or two cycles, I will build this out.

**Comment by derornos** [comment]
```
eoe
"setup": [
  "checkpoints_rule",
  "frost_tokens_rule",
  "tekelili_rule",
  "partner_rule",
  "alert_rule"
],

fof
"setup": [
  "checkpoints_rule",
  "alarm_level",
  "isamara_rule",
  "patrol_rule",
  "game_icons_rule",
  "mulligans_rule",
  "wellspring_of_fortune"
],

gob
"setup": [
  "explore_rule",
  "story_cards",
  "strength_of_the_abyss",
  "taken_by_the_abyss"
],

ptc
"setup": [
  "check_reprint_version",
  "hidden_keyword",
  "doubt_and_conviction",
  "story_cards"
],

tcu
"setup": [
  "haunted_rule",
  "alert_rule",
  "story_cards_rule"
],

tdea
"setup": [
  "alert",
  "story",
  "swarming",
  "hidden"
],

tdeb
"setup": [
  "alert",
  "story",
  "swarming",
  "hidden"
],

tfa
"setup": [
  "supplies",
  "vengeance",
  "explore"
],

tic
"setup": [
  "keys_rule",
  "flood_token_rule"
],

tskc
"setup": [
  "around_the_world",
  "keys_rule",
  "keys_1",
  "keys_2",
  "keys_3",
  "keys_4",
  "keys_5",
  "red_gloved_man",
  "concealed_x",
  "concealed_x_2",
  "concealed_x_3",
  "concealed_mini_cards",
  "concealed_mini_cards_1",
  "concealed_mini_cards_2",
  "concealed_mini_cards_3",
  "concealed_mini_cards_4",
  "concealed_mini_cards_5",
  "alert_rule",
  "patrol_rule"
],

zce
"setup": [
  "saga",
  "listening"
],

zcf
"setup": [
  "quote",
  "notice_rule",
  "non_euclidean_rule"
],

zcp
"setup": [
  "quote",
  "maybe_draw_weakness"
],

zdm
"setup": [
  "scan",
  "memories",
  "alert"
],

zhod
"setup": [
  "quote",
  "information_on_kurtz",
  "act_decks",
  "darkness_calls",
  "exile",
  "story_cards",
  "alert",
  "bonded",
  "explore"
],

rttic
"setup": [
  "deep_one_investigators",
  "tidal_tunnels_rule",
  "keys_rule",
  "flood_token_rule"
],

zsas
"setup": [
  "saga",
  "listening"
]
```

**Comment by zzorba** [comment]
Okay, I'm working on this tomorrow.  I've settled on a schema like this:

https://github.com/zzorba/arkham-cards-data/commit/5f6ced894814ce874fc787abe5b80e4b3f1340e4

Steps to complete it:

1) Move any rules for the whole campaign from campaign.json to core.json file.  Prefix their ids with $, and reference them in the original campaign.json

2) Add a new `"rules": []` array to campaign with title + series of steps for each rule.  This will let me alphabetize them properly.

3) For scenario specific rules, just add a cross-reference to their individual scenario files, in the same format as the `"rules": []` object.  I'll merge this with the campaign rules to present them on each scenario.

I'm going to work on the code to expose this -- if you're able to help redo the json files, I'd appreciate the help.  

No translations should be affected by this process, thankfully, since all the strings already exist.

**Comment by zzorba** [comment]
I'm going to add this in more spots, just have to refactor the scenario page a bit

**Comment by derornos** [comment]
I hope this helps you.
Please check out the following PR.
https://github.com/zzorba/arkham-cards-data/pull/1224
